// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package exam_api

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam_api/internal/data/entity"
)

func newExamineeAnswerQuestionAnswer(db *gorm.DB, opts ...gen.DOOption) examineeAnswerQuestionAnswer {
	_examineeAnswerQuestionAnswer := examineeAnswerQuestionAnswer{}

	_examineeAnswerQuestionAnswer.examineeAnswerQuestionAnswerDo.UseDB(db, opts...)
	_examineeAnswerQuestionAnswer.examineeAnswerQuestionAnswerDo.UseModel(&entity.ExamineeAnswerQuestionAnswer{})

	tableName := _examineeAnswerQuestionAnswer.examineeAnswerQuestionAnswerDo.TableName()
	_examineeAnswerQuestionAnswer.ALL = field.NewAsterisk(tableName)
	_examineeAnswerQuestionAnswer.ID = field.NewString(tableName, "id")
	_examineeAnswerQuestionAnswer.ExamineeAnswerID = field.NewString(tableName, "examinee_answer_id")
	_examineeAnswerQuestionAnswer.QuestionID = field.NewString(tableName, "question_id")
	_examineeAnswerQuestionAnswer.QuestionAnswer = field.NewString(tableName, "question_answer")
	_examineeAnswerQuestionAnswer.Score = field.NewFloat64(tableName, "score")
	_examineeAnswerQuestionAnswer.OptionSign = field.NewString(tableName, "option_sign")
	_examineeAnswerQuestionAnswer.CreatedAt = field.NewTime(tableName, "created_at")
	_examineeAnswerQuestionAnswer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_examineeAnswerQuestionAnswer.CreatedBy = field.NewString(tableName, "created_by")
	_examineeAnswerQuestionAnswer.UpdatedBy = field.NewString(tableName, "updated_by")
	_examineeAnswerQuestionAnswer.DeletedAt = field.NewField(tableName, "deleted_at")

	_examineeAnswerQuestionAnswer.fillFieldMap()

	return _examineeAnswerQuestionAnswer
}

// examineeAnswerQuestionAnswer 答题者答案日志。当考生答题时，就将试卷所有试题，按顺序记录下来
type examineeAnswerQuestionAnswer struct {
	examineeAnswerQuestionAnswerDo

	ALL              field.Asterisk
	ID               field.String  // 主键
	ExamineeAnswerID field.String  // ExamineeAnswer表外键
	QuestionID       field.String  // Question表ID
	QuestionAnswer   field.String  // 问题答案
	Score            field.Float64 // 得分
	OptionSign       field.String  // 选项标记：例如ABCD
	CreatedAt        field.Time    // 创建时间
	UpdatedAt        field.Time    // 更新时间
	CreatedBy        field.String  // 创建人标识
	UpdatedBy        field.String  // 更新人标识
	DeletedAt        field.Field   // 逻辑删除时间

	fieldMap map[string]field.Expr
}

func (e examineeAnswerQuestionAnswer) Table(newTableName string) *examineeAnswerQuestionAnswer {
	e.examineeAnswerQuestionAnswerDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e examineeAnswerQuestionAnswer) As(alias string) *examineeAnswerQuestionAnswer {
	e.examineeAnswerQuestionAnswerDo.DO = *(e.examineeAnswerQuestionAnswerDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *examineeAnswerQuestionAnswer) updateTableName(table string) *examineeAnswerQuestionAnswer {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.ExamineeAnswerID = field.NewString(table, "examinee_answer_id")
	e.QuestionID = field.NewString(table, "question_id")
	e.QuestionAnswer = field.NewString(table, "question_answer")
	e.Score = field.NewFloat64(table, "score")
	e.OptionSign = field.NewString(table, "option_sign")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.CreatedBy = field.NewString(table, "created_by")
	e.UpdatedBy = field.NewString(table, "updated_by")
	e.DeletedAt = field.NewField(table, "deleted_at")

	e.fillFieldMap()

	return e
}

func (e *examineeAnswerQuestionAnswer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *examineeAnswerQuestionAnswer) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["examinee_answer_id"] = e.ExamineeAnswerID
	e.fieldMap["question_id"] = e.QuestionID
	e.fieldMap["question_answer"] = e.QuestionAnswer
	e.fieldMap["score"] = e.Score
	e.fieldMap["option_sign"] = e.OptionSign
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["created_by"] = e.CreatedBy
	e.fieldMap["updated_by"] = e.UpdatedBy
	e.fieldMap["deleted_at"] = e.DeletedAt
}

func (e examineeAnswerQuestionAnswer) clone(db *gorm.DB) examineeAnswerQuestionAnswer {
	e.examineeAnswerQuestionAnswerDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e examineeAnswerQuestionAnswer) replaceDB(db *gorm.DB) examineeAnswerQuestionAnswer {
	e.examineeAnswerQuestionAnswerDo.ReplaceDB(db)
	return e
}

type examineeAnswerQuestionAnswerDo struct{ gen.DO }

func (e examineeAnswerQuestionAnswerDo) Debug() *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Debug())
}

func (e examineeAnswerQuestionAnswerDo) WithContext(ctx context.Context) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e examineeAnswerQuestionAnswerDo) ReadDB() *examineeAnswerQuestionAnswerDo {
	return e.Clauses(dbresolver.Read)
}

func (e examineeAnswerQuestionAnswerDo) WriteDB() *examineeAnswerQuestionAnswerDo {
	return e.Clauses(dbresolver.Write)
}

func (e examineeAnswerQuestionAnswerDo) Session(config *gorm.Session) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Session(config))
}

func (e examineeAnswerQuestionAnswerDo) Clauses(conds ...clause.Expression) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Returning(value interface{}, columns ...string) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e examineeAnswerQuestionAnswerDo) Not(conds ...gen.Condition) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Or(conds ...gen.Condition) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Select(conds ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Where(conds ...gen.Condition) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Order(conds ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Distinct(cols ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e examineeAnswerQuestionAnswerDo) Omit(cols ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e examineeAnswerQuestionAnswerDo) Join(table schema.Tabler, on ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e examineeAnswerQuestionAnswerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e examineeAnswerQuestionAnswerDo) RightJoin(table schema.Tabler, on ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e examineeAnswerQuestionAnswerDo) Group(cols ...field.Expr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e examineeAnswerQuestionAnswerDo) Having(conds ...gen.Condition) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e examineeAnswerQuestionAnswerDo) Limit(limit int) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e examineeAnswerQuestionAnswerDo) Offset(offset int) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e examineeAnswerQuestionAnswerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e examineeAnswerQuestionAnswerDo) Unscoped() *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Unscoped())
}

func (e examineeAnswerQuestionAnswerDo) Create(values ...*entity.ExamineeAnswerQuestionAnswer) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e examineeAnswerQuestionAnswerDo) CreateInBatches(values []*entity.ExamineeAnswerQuestionAnswer, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e examineeAnswerQuestionAnswerDo) Save(values ...*entity.ExamineeAnswerQuestionAnswer) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e examineeAnswerQuestionAnswerDo) First() (*entity.ExamineeAnswerQuestionAnswer, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ExamineeAnswerQuestionAnswer), nil
	}
}

func (e examineeAnswerQuestionAnswerDo) Take() (*entity.ExamineeAnswerQuestionAnswer, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ExamineeAnswerQuestionAnswer), nil
	}
}

func (e examineeAnswerQuestionAnswerDo) Last() (*entity.ExamineeAnswerQuestionAnswer, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ExamineeAnswerQuestionAnswer), nil
	}
}

func (e examineeAnswerQuestionAnswerDo) Find() ([]*entity.ExamineeAnswerQuestionAnswer, error) {
	result, err := e.DO.Find()
	return result.([]*entity.ExamineeAnswerQuestionAnswer), err
}

func (e examineeAnswerQuestionAnswerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.ExamineeAnswerQuestionAnswer, err error) {
	buf := make([]*entity.ExamineeAnswerQuestionAnswer, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e examineeAnswerQuestionAnswerDo) FindInBatches(result *[]*entity.ExamineeAnswerQuestionAnswer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e examineeAnswerQuestionAnswerDo) Attrs(attrs ...field.AssignExpr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e examineeAnswerQuestionAnswerDo) Assign(attrs ...field.AssignExpr) *examineeAnswerQuestionAnswerDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e examineeAnswerQuestionAnswerDo) Joins(fields ...field.RelationField) *examineeAnswerQuestionAnswerDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e examineeAnswerQuestionAnswerDo) Preload(fields ...field.RelationField) *examineeAnswerQuestionAnswerDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e examineeAnswerQuestionAnswerDo) FirstOrInit() (*entity.ExamineeAnswerQuestionAnswer, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ExamineeAnswerQuestionAnswer), nil
	}
}

func (e examineeAnswerQuestionAnswerDo) FirstOrCreate() (*entity.ExamineeAnswerQuestionAnswer, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.ExamineeAnswerQuestionAnswer), nil
	}
}

func (e examineeAnswerQuestionAnswerDo) FindByPage(offset int, limit int) (result []*entity.ExamineeAnswerQuestionAnswer, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e examineeAnswerQuestionAnswerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e examineeAnswerQuestionAnswerDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e examineeAnswerQuestionAnswerDo) Delete(models ...*entity.ExamineeAnswerQuestionAnswer) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *examineeAnswerQuestionAnswerDo) withDO(do gen.Dao) *examineeAnswerQuestionAnswerDo {
	e.DO = *do.(*gen.DO)
	return e
}
