// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package exam_api

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam_api/internal/data/entity"
)

func newSalesPaperDimension(db *gorm.DB, opts ...gen.DOOption) salesPaperDimension {
	_salesPaperDimension := salesPaperDimension{}

	_salesPaperDimension.salesPaperDimensionDo.UseDB(db, opts...)
	_salesPaperDimension.salesPaperDimensionDo.UseModel(&entity.SalesPaperDimension{})

	tableName := _salesPaperDimension.salesPaperDimensionDo.TableName()
	_salesPaperDimension.ALL = field.NewAsterisk(tableName)
	_salesPaperDimension.ID = field.NewString(tableName, "id")
	_salesPaperDimension.SalesPaperID = field.NewString(tableName, "sales_paper_id")
	_salesPaperDimension.Name = field.NewString(tableName, "name")
	_salesPaperDimension.AverageMark = field.NewFloat64(tableName, "average_mark")
	_salesPaperDimension.StandardMark = field.NewFloat64(tableName, "standard_mark")
	_salesPaperDimension.Description = field.NewString(tableName, "description")
	_salesPaperDimension.MaxScore = field.NewFloat64(tableName, "max_score")
	_salesPaperDimension.MinScore = field.NewFloat64(tableName, "min_score")
	_salesPaperDimension.IsChoose = field.NewBool(tableName, "is_choose")
	_salesPaperDimension.CreatedAt = field.NewTime(tableName, "created_at")
	_salesPaperDimension.UpdatedAt = field.NewTime(tableName, "updated_at")
	_salesPaperDimension.CreatedBy = field.NewString(tableName, "created_by")
	_salesPaperDimension.UpdatedBy = field.NewString(tableName, "updated_by")
	_salesPaperDimension.DeletedAt = field.NewField(tableName, "deleted_at")

	_salesPaperDimension.fillFieldMap()

	return _salesPaperDimension
}

// salesPaperDimension 维度表
type salesPaperDimension struct {
	salesPaperDimensionDo

	ALL          field.Asterisk
	ID           field.String  // 主键
	SalesPaperID field.String  // 售卷表外键
	Name         field.String  // 维度名称
	AverageMark  field.Float64 // 平均分
	StandardMark field.Float64 // 标准差
	Description  field.String  // 描述
	MaxScore     field.Float64 // 最高分数上限
	MinScore     field.Float64 // 最低分数下限
	IsChoose     field.Bool    // 是否可选择该维度
	CreatedAt    field.Time    // 创建时间
	UpdatedAt    field.Time    // 更新时间
	CreatedBy    field.String  // 创建人标识
	UpdatedBy    field.String  // 更新人标识
	DeletedAt    field.Field   // 逻辑删除时间

	fieldMap map[string]field.Expr
}

func (s salesPaperDimension) Table(newTableName string) *salesPaperDimension {
	s.salesPaperDimensionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s salesPaperDimension) As(alias string) *salesPaperDimension {
	s.salesPaperDimensionDo.DO = *(s.salesPaperDimensionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *salesPaperDimension) updateTableName(table string) *salesPaperDimension {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.SalesPaperID = field.NewString(table, "sales_paper_id")
	s.Name = field.NewString(table, "name")
	s.AverageMark = field.NewFloat64(table, "average_mark")
	s.StandardMark = field.NewFloat64(table, "standard_mark")
	s.Description = field.NewString(table, "description")
	s.MaxScore = field.NewFloat64(table, "max_score")
	s.MinScore = field.NewFloat64(table, "min_score")
	s.IsChoose = field.NewBool(table, "is_choose")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewString(table, "created_by")
	s.UpdatedBy = field.NewString(table, "updated_by")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *salesPaperDimension) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *salesPaperDimension) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["sales_paper_id"] = s.SalesPaperID
	s.fieldMap["name"] = s.Name
	s.fieldMap["average_mark"] = s.AverageMark
	s.fieldMap["standard_mark"] = s.StandardMark
	s.fieldMap["description"] = s.Description
	s.fieldMap["max_score"] = s.MaxScore
	s.fieldMap["min_score"] = s.MinScore
	s.fieldMap["is_choose"] = s.IsChoose
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s salesPaperDimension) clone(db *gorm.DB) salesPaperDimension {
	s.salesPaperDimensionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s salesPaperDimension) replaceDB(db *gorm.DB) salesPaperDimension {
	s.salesPaperDimensionDo.ReplaceDB(db)
	return s
}

type salesPaperDimensionDo struct{ gen.DO }

func (s salesPaperDimensionDo) Debug() *salesPaperDimensionDo {
	return s.withDO(s.DO.Debug())
}

func (s salesPaperDimensionDo) WithContext(ctx context.Context) *salesPaperDimensionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s salesPaperDimensionDo) ReadDB() *salesPaperDimensionDo {
	return s.Clauses(dbresolver.Read)
}

func (s salesPaperDimensionDo) WriteDB() *salesPaperDimensionDo {
	return s.Clauses(dbresolver.Write)
}

func (s salesPaperDimensionDo) Session(config *gorm.Session) *salesPaperDimensionDo {
	return s.withDO(s.DO.Session(config))
}

func (s salesPaperDimensionDo) Clauses(conds ...clause.Expression) *salesPaperDimensionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s salesPaperDimensionDo) Returning(value interface{}, columns ...string) *salesPaperDimensionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s salesPaperDimensionDo) Not(conds ...gen.Condition) *salesPaperDimensionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s salesPaperDimensionDo) Or(conds ...gen.Condition) *salesPaperDimensionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s salesPaperDimensionDo) Select(conds ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s salesPaperDimensionDo) Where(conds ...gen.Condition) *salesPaperDimensionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s salesPaperDimensionDo) Order(conds ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s salesPaperDimensionDo) Distinct(cols ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s salesPaperDimensionDo) Omit(cols ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s salesPaperDimensionDo) Join(table schema.Tabler, on ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s salesPaperDimensionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s salesPaperDimensionDo) RightJoin(table schema.Tabler, on ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s salesPaperDimensionDo) Group(cols ...field.Expr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s salesPaperDimensionDo) Having(conds ...gen.Condition) *salesPaperDimensionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s salesPaperDimensionDo) Limit(limit int) *salesPaperDimensionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s salesPaperDimensionDo) Offset(offset int) *salesPaperDimensionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s salesPaperDimensionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *salesPaperDimensionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s salesPaperDimensionDo) Unscoped() *salesPaperDimensionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s salesPaperDimensionDo) Create(values ...*entity.SalesPaperDimension) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s salesPaperDimensionDo) CreateInBatches(values []*entity.SalesPaperDimension, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s salesPaperDimensionDo) Save(values ...*entity.SalesPaperDimension) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s salesPaperDimensionDo) First() (*entity.SalesPaperDimension, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SalesPaperDimension), nil
	}
}

func (s salesPaperDimensionDo) Take() (*entity.SalesPaperDimension, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SalesPaperDimension), nil
	}
}

func (s salesPaperDimensionDo) Last() (*entity.SalesPaperDimension, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SalesPaperDimension), nil
	}
}

func (s salesPaperDimensionDo) Find() ([]*entity.SalesPaperDimension, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SalesPaperDimension), err
}

func (s salesPaperDimensionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SalesPaperDimension, err error) {
	buf := make([]*entity.SalesPaperDimension, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s salesPaperDimensionDo) FindInBatches(result *[]*entity.SalesPaperDimension, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s salesPaperDimensionDo) Attrs(attrs ...field.AssignExpr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s salesPaperDimensionDo) Assign(attrs ...field.AssignExpr) *salesPaperDimensionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s salesPaperDimensionDo) Joins(fields ...field.RelationField) *salesPaperDimensionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s salesPaperDimensionDo) Preload(fields ...field.RelationField) *salesPaperDimensionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s salesPaperDimensionDo) FirstOrInit() (*entity.SalesPaperDimension, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SalesPaperDimension), nil
	}
}

func (s salesPaperDimensionDo) FirstOrCreate() (*entity.SalesPaperDimension, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SalesPaperDimension), nil
	}
}

func (s salesPaperDimensionDo) FindByPage(offset int, limit int) (result []*entity.SalesPaperDimension, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s salesPaperDimensionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s salesPaperDimensionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s salesPaperDimensionDo) Delete(models ...*entity.SalesPaperDimension) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *salesPaperDimensionDo) withDO(do gen.Dao) *salesPaperDimensionDo {
	s.DO = *do.(*gen.DO)
	return s
}
