// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDimensionComment = "dimension_comment"

// DimensionComment 维度评语表
type DimensionComment struct {
	ID        string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                           // 主键
	LowScore  float64        `gorm:"column:low_score;not null;default:0.00;comment:分数下限" json:"low_score"`                // 分数下限
	UpScore   float64        `gorm:"column:up_score;not null;default:0.00;comment:分数上限" json:"up_score"`                  // 分数上限
	Content   string         `gorm:"column:content;not null;comment:评语" json:"content"`                                   // 评语
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName DimensionComment's table name
func (*DimensionComment) TableName() string {
	return TableNameDimensionComment
}
