// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamineeAnswer = "examinee_answer"

// ExamineeAnswer 考生答题记录表
type ExamineeAnswer struct {
	ID                              string         `gorm:"column:id;primaryKey;comment:主键（雪花ID）" json:"id"`                                                                   // 主键（雪花ID）
	SalesPaperID                    string         `gorm:"column:sales_paper_id;not null;comment:试卷ID" json:"sales_paper_id"`                                                 // 试卷ID
	ExamineeID                      string         `gorm:"column:examinee_id;not null;comment:考生唯一标识" json:"examinee_id"`                                                     // 考生唯一标识
	ExamineeSalesPaperAssociationID string         `gorm:"column:examinee_sales_paper_association_id;not null;comment:考生试卷关联idID" json:"examinee_sales_paper_association_id"` // 考生试卷关联idID
	Score                           float64        `gorm:"column:score;not null;default:0.00;comment:答题标准分" json:"score"`                                                     // 答题标准分
	BeginTestTime                   time.Time      `gorm:"column:begin_test_time;not null;default:CURRENT_TIMESTAMP;comment:答题开始时刻" json:"begin_test_time"`                   // 答题开始时刻
	SubmitTime                      *time.Time     `gorm:"column:submit_time;comment:答题提交时刻" json:"submit_time"`                                                              // 答题提交时刻
	CompleteQuestionNum             int32          `gorm:"column:complete_question_num;not null;comment:完成题目个数" json:"complete_question_num"`                                 // 完成题目个数
	LastActionTime                  *time.Time     `gorm:"column:last_action_time;comment:最后活动时刻" json:"last_action_time"`                                                    // 最后活动时刻
	Comparability                   int32          `gorm:"column:comparability;not null;comment:匹配度" json:"comparability"`                                                    // 匹配度
	Deadline                        time.Time      `gorm:"column:deadline;not null;comment:试卷截止时刻" json:"deadline"`                                                           // 试卷截止时刻
	Usability                       int32          `gorm:"column:usability;not null;default:1;comment:试卷有效性（1~4）" json:"usability"`                                           // 试卷有效性（1~4）
	RemainingTimelimit              int32          `gorm:"column:remaining_timelimit;not null;comment:考试剩余时长" json:"remaining_timelimit"`                                     // 考试剩余时长
	CreatedAt                       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt                       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                               // 更新时间
	CreatedBy                       string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                                                        // 创建人标识
	UpdatedBy                       string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                                                        // 更新人标识
	DeletedAt                       gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                                                // 逻辑删除时间
}

// TableName ExamineeAnswer's table name
func (*ExamineeAnswer) TableName() string {
	return TableNameExamineeAnswer
}
