// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamineeEmailRecord = "examinee_email_record"

// ExamineeEmailRecord 邮件发送日志
type ExamineeEmailRecord struct {
	ID                              string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                                                         // 主键
	SalesPaperID                    string         `gorm:"column:sales_paper_id;not null;comment:SalesPaper表的外键" json:"sales_paper_id"`                                       // SalesPaper表的外键
	ExamineeID                      string         `gorm:"column:examinee_id;not null;comment:考生ID" json:"examinee_id"`                                                       // 考生ID
	ExamineeSalesPaperAssociationID string         `gorm:"column:examinee_sales_paper_association_id;not null;comment:考生试卷关联idID" json:"examinee_sales_paper_association_id"` // 考生试卷关联idID
	Title                           string         `gorm:"column:title;not null;comment:邮件标题" json:"title"`                                                                   // 邮件标题
	Content                         string         `gorm:"column:content;comment:邮件内容" json:"content"`                                                                        // 邮件内容
	ReceiverEmail                   string         `gorm:"column:receiver_email;not null;comment:接收人邮箱" json:"receiver_email"`                                                // 接收人邮箱
	SendTime                        *time.Time     `gorm:"column:send_time;comment:发送时刻" json:"send_time"`                                                                    // 发送时刻
	EmailStatus                     int32          `gorm:"column:email_status;not null;default:1;comment:邮件状态：1.未发送，2.已发送，3.发送失败" json:"email_status"`                        // 邮件状态：1.未发送，2.已发送，3.发送失败
	SenderEmail                     string         `gorm:"column:sender_email;not null;comment:发件人邮箱" json:"sender_email"`                                                    // 发件人邮箱
	CopyReceiverEmail               string         `gorm:"column:copy_receiver_email;not null;comment:抄送人邮箱" json:"copy_receiver_email"`                                      // 抄送人邮箱
	Attachment                      string         `gorm:"column:attachment;not null;comment:附件" json:"attachment"`                                                           // 附件
	IsFalseAddress                  bool           `gorm:"column:is_false_address;not null;comment:是否为错误地址" json:"is_false_address"`                                          // 是否为错误地址
	CreatedAt                       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt                       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                               // 更新时间
	CreatedBy                       string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                                                        // 创建人标识
	UpdatedBy                       string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                                                        // 更新人标识
	DeletedAt                       gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                                                // 逻辑删除时间
}

// TableName ExamineeEmailRecord's table name
func (*ExamineeEmailRecord) TableName() string {
	return TableNameExamineeEmailRecord
}
