// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamineeSalesPaperAssociation = "examinee_sales_paper_association"

// ExamineeSalesPaperAssociation 正式参加测评的考生
type ExamineeSalesPaperAssociation struct {
	ID             string         `gorm:"column:id;primaryKey;comment:主键（Guid）" json:"id"`                                            // 主键（Guid）
	SalesPaperID   string         `gorm:"column:sales_paper_id;not null;comment:SalesPaper表的外键" json:"sales_paper_id"`                // SalesPaper表的外键
	SalesPaperName string         `gorm:"column:sales_paper_name;not null;comment:考试名称" json:"sales_paper_name"`                      // 考试名称
	ExamineeID     string         `gorm:"column:examinee_id;not null;comment:关联考生ID" json:"examinee_id"`                              // 关联考生ID
	EmailStatus    int32          `gorm:"column:email_status;not null;default:1;comment:邮件状态：1.未发送，2.已发送，3.发送失败" json:"email_status"` // 邮件状态：1.未发送，2.已发送，3.发送失败
	StageNumber    int32          `gorm:"column:stage_number;not null;comment:阶段编号（0~5）" json:"stage_number"`                         // 阶段编号（0~5）
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`        // 更新时间
	CreatedBy      string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                                 // 创建人标识
	UpdatedBy      string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                                 // 更新人标识
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                         // 逻辑删除时间
}

// TableName ExamineeSalesPaperAssociation's table name
func (*ExamineeSalesPaperAssociation) TableName() string {
	return TableNameExamineeSalesPaperAssociation
}
