// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExaminee = "examinee"

// Examinee 正式参加测评的考生
type Examinee struct {
	ID           string         `gorm:"column:id;primaryKey;comment:主键（Guid）" json:"id"`                                     // 主键（Guid）
	UserName     string         `gorm:"column:user_name;not null;comment:用户名" json:"user_name"`                              // 用户名
	HashPassword string         `gorm:"column:hash_password;not null;comment:密码" json:"hash_password"`                       // 密码
	Status       int32          `gorm:"column:status;not null;comment:状态：1.已激活;0.未激活" json:"status"`                         // 状态：1.已激活;0.未激活
	Email        string         `gorm:"column:email;not null;comment:邮箱" json:"email"`                                       // 邮箱
	Phone        string         `gorm:"column:phone;not null;comment:电话" json:"phone"`                                       // 电话
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy    string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy    string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName Examinee's table name
func (*Examinee) TableName() string {
	return TableNameExaminee
}
