// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamEvent = "exam_events"

// ExamEvent mapped from table <exam_events>
type ExamEvent struct {
	ID               string         `gorm:"column:id;primaryKey" json:"id"`
	SessionID        string         `gorm:"column:session_id;primaryKey" json:"session_id"`
	ExamToken        string         `gorm:"column:exam_token;comment:JWT" json:"exam_token"`                                                                                                // JWT
	ExamineeAnswerID string         `gorm:"column:examinee_answer_id;comment:examineeanswerid" json:"examinee_answer_id"`                                                                   // examineeanswerid
	EventType        string         `gorm:"column:event_type;not null;comment:事件类型：heartbeat, exam_reentry, switch_tab, copy, paste, visibility_hidden, submit, time_up" json:"event_type"` // 事件类型：heartbeat, exam_reentry, switch_tab, copy, paste, visibility_hidden, submit, time_up
	IP               string         `gorm:"column:ip;not null;comment:客户端 IP" json:"ip"`                                                                                                    // 客户端 IP
	UserAgent        string         `gorm:"column:user_agent;comment:浏览器 User-Agent" json:"user_agent"`                                                                                     // 浏览器 User-Agent
	Meta             string         `gorm:"column:meta;comment:事件附加信息，如：gap_seconds, used_duration, question_count" json:"meta"`                                                            // 事件附加信息，如：gap_seconds, used_duration, question_count
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                            // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                            // 更新时间
	CreatedBy        string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                                                                                     // 创建人标识
	UpdatedBy        string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                                                                                     // 更新人标识
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                                                                             // 逻辑删除时间
}

// TableName ExamEvent's table name
func (*ExamEvent) TableName() string {
	return TableNameExamEvent
}
