// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExamineeAnswerDimensionScore = "examinee_answer_dimension_score"

// ExamineeAnswerDimensionScore 记录答卷维度总分
type ExamineeAnswerDimensionScore struct {
	ID                     string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                                           // 主键
	ExamineeAnswerID       string         `gorm:"column:examinee_answer_id;not null;comment:ExamineeAnswer表外键" json:"examinee_answer_id"`              // ExamineeAnswer表外键
	DimensionID            string         `gorm:"column:dimension_id;not null;comment:Dimension表的ID" json:"dimension_id"`                              // Dimension表的ID
	DimensionRawScore      float64        `gorm:"column:dimension_raw_score;not null;default:0.00;comment:维度原始分" json:"dimension_raw_score"`           // 维度原始分
	DimensionStandardScore float64        `gorm:"column:dimension_standard_score;not null;default:0.00;comment:维度标准分" json:"dimension_standard_score"` // 维度标准分
	CreatedAt              time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                 // 创建时间
	UpdatedAt              time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                 // 更新时间
	CreatedBy              string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                                          // 创建人标识
	UpdatedBy              string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                                          // 更新人标识
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                                  // 逻辑删除时间
}

// TableName ExamineeAnswerDimensionScore's table name
func (*ExamineeAnswerDimensionScore) TableName() string {
	return TableNameExamineeAnswerDimensionScore
}
