// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestion = "question"

// Question 存放试题
type Question struct {
	ID             string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                           // 主键
	DimensionID    string         `gorm:"column:dimension_id;not null;comment:维度表外键" json:"dimension_id"`                      // 维度表外键
	SalesPaperID   string         `gorm:"column:sales_paper_id;not null;comment:试卷表外键" json:"sales_paper_id"`                  // 试卷表外键
	Title          string         `gorm:"column:title;not null;comment:题干" json:"title"`                                       // 题干
	Remark         string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                     // 备注
	QuestionTypeID int32          `gorm:"column:question_type_id;not null;comment:试题类型ID" json:"question_type_id"`             // 试题类型ID
	Order_         int32          `gorm:"column:order;not null;comment:排序" json:"order"`                                       // 排序
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy      string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy      string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
