// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestionOption = "question_option"

// QuestionOption 试题选项
type QuestionOption struct {
	ID          string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                           // 主键
	QuestionID  string         `gorm:"column:question_id;not null;comment:Question表外键。当选项与维度直" json:"question_id"`          // Question表外键。当选项与维度直
	Score       float64        `gorm:"column:score;not null;default:0.00;comment:选项分数" json:"score"`                        // 选项分数
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`                           // 描述
	DimensionID string         `gorm:"column:dimension_id;not null;comment:维度ID，适用于选项直接绑定维" json:"dimension_id"`            // 维度ID，适用于选项直接绑定维
	Order_      int32          `gorm:"column:order;not null;comment:排序" json:"order"`                                       // 排序
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy   string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy   string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName QuestionOption's table name
func (*QuestionOption) TableName() string {
	return TableNameQuestionOption
}
