// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSalesPaperComment = "sales_paper_comment"

// SalesPaperComment 售卷评语表，不同区间对应不同评语
type SalesPaperComment struct {
	ID           string         `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                           // 主键
	SalesPaperID string         `gorm:"column:sales_paper_id;not null;comment:SalesPaper表的外键" json:"sales_paper_id"`         // SalesPaper表的外键
	Content      string         `gorm:"column:content;not null;comment:评语" json:"content"`                                   // 评语
	UpScore      float64        `gorm:"column:up_score;not null;default:0.00;comment:上限分数区分点" json:"up_score"`               // 上限分数区分点
	LowScore     float64        `gorm:"column:low_score;not null;default:0.00;comment:下限分数区分点" json:"low_score"`             // 下限分数区分点
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy    string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy    string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName SalesPaperComment's table name
func (*SalesPaperComment) TableName() string {
	return TableNameSalesPaperComment
}
